import React from 'react';
import { Row, Col } from 'reactstrap';
import styled from 'styled-components';

import { PrimaryButton } from '../../styled-components/Buttons';
import { Small, LABEL } from '../../styled-components/Typography';

const Modal2FA = ({bgStyles, mainStyles, verify, onCancel, args, resetTwoFA, data}) => {
  let msg = "I have a problem with 2FA";
  let btn = "Confirm";
  if (data && data.type === 'login') {
    msg = "I'm not able to log in with 2FA";
    btn = "Log In";
  }

  return (
    <StyledDiv>
      <div className="modal-dialog custom">
        <div className="modal-content">
          <form
            className="form"
            onSubmit={e => {
              e.preventDefault();
              verify(e.target.code.value);
            }}
          >
            <div className="modal-header">
              <img src="/img/logo.svg" width="82" height="36" />
              <div className="title">2-factor Authentication is enabled</div>
              <img
                src="/img/icons/ico-cross.png"
                width="20"
                height="20"
                onClick={onCancel}
              />
            </div>

            <div className="modal-body">
              <div className="description">
                <img src="/img/smartphone.svg" width="52" />
                <div className="text-center">Please enter the 6-digit code generated by the authentication app on your device.</div>
              </div>
              
              <div className="form-group">
                <LABEL>Authentication code</LABEL>
                <input
                  className="form-control"
                  placeholder=""
                  type="text"
                  name="code"
                  maxLength="6"
                  autoFocus
                />
                <Small className="pull-right m-t-5" style={{color:'#a5acb5'}}>
                  Example: 123456
                </Small>
              </div>
            </div>

            <div className="modal-footer justify-content-center">
              <div className="button-wrapper">
                <PrimaryButton block>{btn}</PrimaryButton>
              </div>
              <div className="text-center">
                <a href="javascript:void(0);" onClick={() => resetTwoFA(args[0], data)}>{msg}</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </StyledDiv>
  );
};

const StyledDiv = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  width: 100%;
  height: 100vh;
  z-index: 3;
  background-color: rgba(0, 0, 0, 0.4);
  display: flex;
  align-items: center;
  justify-content: center;

  .modal-dialog.custom {
    width: 520px;
    background-color: #2E3A4D;
    color: white;
    padding: 0;

    .modal-content {
      background-color: #2E3A4D;
      width: 520px;

      .modal-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        position: relative;
        background-color: #2E3A4D;
        box-shadow: 0 3px 3px #00000045;
  
        .title {
          position: absolute;
          left: 0;
          right: 0;
          text-align: center;
          font-weight: 400;
          font-size: 16px;
        }
  
        img {
          z-index: 4;
        }
      }
    }
    
    .modal-body {
      padding: 30px 100px;
      text-align: center;
      color: #D2D7D8;

      .form-group {
        margin-top: 30px;

        label {
          font-size: 14px;
          text-align: left;
          width: 100%;
          color: #D2D7D8;
        }

        input {
          background: #374B66;
          border: none;
          border-radius: 2px;
          color: white;
          font-size: 16px;
          padding: 12px;
        }
      }

      .description {
        display: flex;
        justify-content: space-between;
        img {
          margin-right: 10px;
        }
      }
    }

    .modal-footer {
      padding: 0 100px 30px 100px;
      flex-direction: column;
      
      .button-wrapper {
        width: 100%;
        margin-bottom: 5px;

        button {
          padding: 12px 32px;
        }
      }
    }
  }
`

export default Modal2FA;
