const countries = [
  {key: 'AL', name: 'Albania'},
  {key: 'DZ', name: 'Algeria'},
  {key: 'AS', name: 'American Samoa'},
  {key: 'AD', name: 'Andorra'},
  {key: 'AO', name: 'Angola'},
  {key: 'AG', name: 'Antigua and Barbuda'},
  {key: 'AR', name: 'Argentina'},
  {key: 'AM', name: 'Armenia'},
  {key: 'AW', name: 'Aruba'},
  {key: 'AU', name: 'Australia'},
  {key: 'AT', name: 'Austria'},
  {key: 'AZ', name: 'Azerbaijan'},
  {key: 'BS', name: 'Bahamas'},
  {key: 'BH', name: 'Bahrain'},
  {key: 'BD', name: 'Bangladesh'},
  {key: 'BB', name: 'Barbados'},
  {key: 'BY', name: 'Belarus'},
  {key: 'BE', name: 'Belgium'},
  {key: 'BZ', name: 'Belize'},
  {key: 'BJ', name: 'Benin'},
  {key: 'BM', name: 'Bermuda'},
  {key: 'BT', name: 'Bhutan'},
  {key: 'BO', name: 'Bolivia'},
  {key: 'BA', name: 'Bosnia and Herzegovina'},
  {key: 'BW', name: 'Botswana'},
  {key: 'BR', name: 'Brazil'},
  {key: 'IO', name: 'British Indian Ocean Territory'},
  {key: 'BN', name: 'Brunei Darussalam'},
  {key: 'BG', name: 'Bulgaria'},
  {key: 'BF', name: 'Burkina Faso'},
  {key: 'BI', name: 'Burundi'},
  {key: 'KH', name: 'Cambodia'},
  {key: 'CM', name: 'Cameroon'},
  {key: 'CA', name: 'Canada'},
  {key: 'CV', name: 'Cape Verde'},
  {key: 'KY', name: 'Cayman Islands'},
  {key: 'CL', name: 'Chile'},
  {key: 'CN', name: 'China'},
  {key: 'HK', name: 'Hong Kong, SAR China'},
  {key: 'MO', name: 'Macao, SAR China'},
  {key: 'CO', name: 'Colombia'},
  {key: 'KM', name: 'Comoros'},
  {key: 'CD', name: 'Congo, (Kinshasa)'},
  {key: 'CR', name: 'Costa Rica'},
  {key: 'CI', name: "Côte d'Ivoire"},
  {key: 'HR', name: 'Croatia'},
  {key: 'CU', name: 'Cuba'},
  {key: 'CY', name: 'Cyprus'},
  {key: 'CZ', name: 'Czech Republic'},
  {key: 'DK', name: 'Denmark'},
  {key: 'DO', name: 'Dominican Republic'},
  {key: 'EC', name: 'Ecuador'},
  {key: 'EG', name: 'Egypt'},
  {key: 'SV', name: 'El Salvador'},
  {key: 'GQ', name: 'Equatorial Guinea'},
  {key: 'ER', name: 'Eritrea'},
  {key: 'EE', name: 'Estonia'},
  {key: 'FJ', name: 'Fiji'},
  {key: 'FI', name: 'Finland'},
  {key: 'FR', name: 'France'},
  {key: 'GA', name: 'Gabon'},
  {key: 'GM', name: 'Gambia'},
  {key: 'GE', name: 'Georgia'},
  {key: 'DE', name: 'Germany'},
  {key: 'GH', name: 'Ghana'},
  {key: 'GR', name: 'Greece'},
  {key: 'GD', name: 'Grenada'},
  {key: 'GU', name: 'Guam'},
  {key: 'GT', name: 'Guatemala'},
  {key: 'GW', name: 'Guinea-Bissau'},
  {key: 'GY', name: 'Guyana'},
  {key: 'HT', name: 'Haiti'},
  {key: 'HN', name: 'Honduras'},
  {key: 'HU', name: 'Hungary'},
  {key: 'IS', name: 'Iceland'},
  {key: 'IN', name: 'India'},
  {key: 'ID', name: 'Indonesia'},
  {key: 'IR', name: 'Iran, Islamic Republic of'},
  {key: 'IE', name: 'Ireland'},
  {key: 'IL', name: 'Israel'},
  {key: 'IT', name: 'Italy'},
  {key: 'JM', name: 'Jamaica'},
  {key: 'JP', name: 'Japan'},
  {key: 'JO', name: 'Jordan'},
  {key: 'KZ', name: 'Kazakhstan'},
  {key: 'KE', name: 'Kenya'},
  {key: 'KP', name: 'Korea (North)'},
  {key: 'KR', name: 'Korea (South)'},
  {key: 'KW', name: 'Kuwait'},
  {key: 'KG', name: 'Kyrgyzstan'},
  {key: 'LA', name: 'Lao PDR'},
  {key: 'LV', name: 'Latvia'},
  {key: 'LB', name: 'Lebanon'},
  {key: 'LS', name: 'Lesotho'},
  {key: 'LR', name: 'Liberia'},
  {key: 'LY', name: 'Libya'},
  {key: 'LI', name: 'Liechtenstein'},
  {key: 'LT', name: 'Lithuania'},
  {key: 'LU', name: 'Luxembourg'},
  {key: 'MK', name: 'Macedonia, Republic of'},
  {key: 'MG', name: 'Madagascar'},
  {key: 'MW', name: 'Malawi'},
  {key: 'MY', name: 'Malaysia'},
  {key: 'MV', name: 'Maldives'},
  {key: 'ML', name: 'Mali'},
  {key: 'MT', name: 'Malta'},
  {key: 'MH', name: 'Marshall Islands'},
  {key: 'MU', name: 'Mauritius'},
  {key: 'MX', name: 'Mexico'},
  {key: 'FM', name: 'Micronesia, Federated States of'},
  {key: 'MD', name: 'Moldova'},
  {key: 'MC', name: 'Monaco'},
  {key: 'MN', name: 'Mongolia'},
  {key: 'ME', name: 'Montenegro'},
  {key: 'MA', name: 'Morocco'},
  {key: 'MZ', name: 'Mozambique'},
  {key: 'MM', name: 'Myanmar'},
  {key: 'NA', name: 'Namibia'},
  {key: 'NP', name: 'Nepal'},
  {key: 'NL', name: 'Netherlands'},
  {key: 'AN', name: 'Netherlands Antilles'},
  {key: 'NZ', name: 'New Zealand'},
  {key: 'NI', name: 'Nicaragua'},
  {key: 'NE', name: 'Niger'},
  {key: 'NG', name: 'Nigeria'},
  {key: 'MP', name: 'Northern Mariana Islands'},
  {key: 'NO', name: 'Norway'},
  {key: 'OM', name: 'Oman'},
  {key: 'PK', name: 'Pakistan'},
  {key: 'PW', name: 'Palau'},
  {key: 'PS', name: 'Palestinian Territory'},
  {key: 'PA', name: 'Panama'},
  {key: 'PG', name: 'Papua New Guinea'},
  {key: 'PY', name: 'Paraguay'},
  {key: 'PE', name: 'Peru'},
  {key: 'PH', name: 'Philippines'},
  {key: 'PL', name: 'Poland'},
  {key: 'PT', name: 'Portugal'},
  {key: 'PR', name: 'Puerto Rico'},
  {key: 'QA', name: 'Qatar'},
  {key: 'RO', name: 'Romania'},
  {key: 'RU', name: 'Russian Federation'},
  {key: 'RW', name: 'Rwanda'},
  {key: 'KN', name: 'Saint Kitts and Nevis'},
  {key: 'LC', name: 'Saint Lucia'},
  {key: 'VC', name: 'Saint Vincent and Grenadines'},
  {key: 'WS', name: 'Samoa'},
  {key: 'SM', name: 'San Marino'},
  {key: 'SA', name: 'Saudi Arabia'},
  {key: 'SN', name: 'Senegal'},
  {key: 'RS', name: 'Serbia'},
  {key: 'SC', name: 'Seychelles'},
  {key: 'SL', name: 'Sierra Leone'},
  {key: 'SG', name: 'Singapore'},
  {key: 'SK', name: 'Slovakia'},
  {key: 'SI', name: 'Slovenia'},
  {key: 'SB', name: 'Solomon Islands'},
  {key: 'SO', name: 'Somalia'},
  {key: 'ZA', name: 'South Africa'},
  {key: 'SS', name: 'South Sudan'},
  {key: 'ES', name: 'Spain'},
  {key: 'LK', name: 'Sri Lanka'},
  {key: 'SD', name: 'Sudan'},
  {key: 'SR', name: 'Suriname'},
  {key: 'SZ', name: 'Swaziland'},
  {key: 'SE', name: 'Sweden'},
  {key: 'CH', name: 'Switzerland'},
  {key: 'SY', name: 'Syrian Arab Republic (Syria)'},
  {key: 'TW', name: 'Taiwan, Republic of China'},
  {key: 'TJ', name: 'Tajikistan'},
  {key: 'TH', name: 'Thailand'},
  {key: 'TG', name: 'Togo'},
  {key: 'TO', name: 'Tonga'},
  {key: 'TT', name: 'Trinidad and Tobago'},
  {key: 'TN', name: 'Tunisia'},
  {key: 'TR', name: 'Turkey'},
  {key: 'TM', name: 'Turkmenistan'},
  {key: 'TC', name: 'Turks and Caicos Islands'},
  {key: 'TV', name: 'Tuvalu'},
  {key: 'UG', name: 'Uganda'},
  {key: 'UA', name: 'Ukraine'},
  {key: 'AE', name: 'United Arab Emirates'},
  {key: 'GB', name: 'United Kingdom'},
  {key: 'US', name: 'United States of America'},
  {key: 'UY', name: 'Uruguay'},
  {key: 'UZ', name: 'Uzbekistan'},
  {key: 'VE', name: 'Venezuela (Bolivarian Republic)'},
  {key: 'VN', name: 'Viet Nam'},
  {key: 'VI', name: 'Virgin Islands, US'},
  {key: 'ZM', name: 'Zambia'},
  {key: 'ZW', name: 'Zimbabwe'},
];

export default countries;
